libks265dec: add libks265dec decoder
Signed-off-by: Steven Liu <liuqi05@kuaishou.com>
Signed-off-by: Steven Liu <lq@chinaffmpeg.org>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -289,6 +289,7 @@ External library support:
   --enable-libwebp         enable WebP encoding via libwebp [no]
   --enable-libx264         enable H.264 encoding via x264 [no]
   --enable-libx265         enable HEVC encoding via x265 [no]
+  --enable-libks265        enable kuaishou private HEVC decoder via libks265dec.a [no]
   --enable-libxavs         enable AVS encoding via xavs [no]
   --enable-libxavs2        enable AVS2 encoding via xavs2 [no]
   --enable-libxcb          enable X11 grabbing using XCB [autodetect]
@@ -1550,6 +1551,21 @@ require(){
     check_lib $name "$@" || die "ERROR: $name_version not found"
 }
 
+check_lib2(){
+    log check_lib2 "$@"
+    headers="$1"
+    funcs="$2"
+    shift 2
+    check_func_headers "$headers" "$funcs" "$@" && add_extralibs "$@"
+}
+require_kwai(){
+    name="$1"
+    header="$2"
+    func="$3"
+    shift 3
+    check_lib2 $header $func "$@" || die "ERROR: $name not found"
+}
+
 require_cc(){
     log require_cc "$@"
     name="$1"
@@ -1762,6 +1778,7 @@ EXTERNAL_LIBRARY_LIST="
     gcrypt
     gnutls
     jni
+    libks265
     ladspa
     libaom
     libass
@@ -3292,6 +3309,7 @@ libx264_encoder_select="atsc_a53"
 libx264rgb_encoder_deps="libx264 x264_csp_bgr"
 libx264rgb_encoder_select="libx264_encoder"
 libx265_encoder_deps="libx265"
+libks265_decoder_deps="libks265"
 libxavs_encoder_deps="libxavs"
 libxavs2_encoder_deps="libxavs2"
 libxvid_encoder_deps="libxvid"
@@ -6485,6 +6503,30 @@ enabled libx264           && { check_pkg_config libx264 x264 "stdint.h x264.h" x
                              check_cpp_condition libx262 x264.h "X264_MPEG2"
 enabled libx265           && require_pkg_config libx265 x265 x265.h x265_api_get &&
                              require_cpp_condition libx265 x265.h "X265_BUILD >= 70"
+
+if enabled libks265; then
+{
+    if [ "$target_os" = "darwin" ]; then
+    {
+        if enabled libks265_decoder; then
+            require_kwai libks265dec ks265dec.h KS265DecodeFrame -lks265dec
+        fi
+    }
+    elif [ "$target_os" = "linux" ]; then
+    {
+        [ "$arch" = "arm" ] || [ "$arch" = "aarch64" ] || die "ERROR: libks265 on linux requires arch arm (current: $arch)."
+        if enabled libks265_decoder; then
+            require_kwai libks265dec ks265dec.h KS265DecodeFrame -lks265dec
+        fi
+    }
+    else
+    {
+        die "ERROR: libks265's target os must be darwin or android (current: $target_os)"
+    }
+    fi
+}
+fi
+
 enabled libxavs           && require libxavs "stdint.h xavs.h" xavs_encoder_encode "-lxavs $pthreads_extralibs $libm_extralibs"
 enabled libxavs2          && require_pkg_config libxavs2 "xavs2 >= 1.3.0" "stdint.h xavs2.h" xavs2_api_get
 enabled libxvid           && require libxvid xvid.h xvid_global -lxvidcore
